# Generated by Django 5.1.1 on 2024-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
