# Generated by Django 5.1.1 on 2024-10-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_friendrequest_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
